version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:your_secure_password@10.0.2.4/todo_db"
      # DB_HOST: "10.0.2.4"  # CentOS DB服务器IP
      # DB_NAME: "todo_db"
      # DB_USER: "postgres"
      # DB_PASSWORD: "your_secure_password"  # 与DB服务器设置的密码一致
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - todo-network

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: "http://backend:5000"
    ports:
      - "80:8000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
